version: '2'

services:
  traefik:
    image: traefik
    restart: always # Is very important that the load balancer restart with the system
    env_file:
     - ./.env
    networks:
      - traefik
      - portainer_local
      - rocketchat_default
      - iaphpbotman_default
      - iajsbotkit_default
      - placeholder_default
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./traefik.toml:/traefik.toml
      - ./ssl:/etc/traefik/ssl
      - ./acme:/etc/traefik/acme
    labels:
      - "traefik.frontend.rule=Host: traefik.chatopswg.xyz"
    logging:
      options:
        max-size: 10m
        max-file: '3'

# TODO: traefik should autodiscover and join other containers network with no
#       need of update each time this file again (its purpose was to
#       self-discovery with no need for a restart as better replacement to
#       NGinx as load balancer for containers) (fititnt, 2018-02-03 15:37 BRTS)

networks:
  traefik:
    driver: bridge
  rocketchat_default:
    external:
      name: rocketchat_default
  portainer_local:
    external:
      name: portainer_local
  iaphpbotman_default:
    external:
      name: iaphpbotman_default
  iajsbotkit_default:
    external:
      name: iajsbotkit_default
  rocketchat_default:
    external:
      name: rocketchat_default
  placeholder_default:
    external:
      name: placeholder_default
