version: '2'

# This command work getting the traefik file, but the composer version, no
### docker run -p 8080:8080 -p 443:443 -p 80:80 -v $PWD/traefik.toml:/etc/traefik/traefik.toml -v $PWD/ssl:/etc/traefik/ssl -v $PWD/acme:/etc/traefik/acme -v /var/run/docker.sock:/var/run/docker.sock --name xpto4 traefik:v1.5.0-rc5

services:
  traefik:
    image: traefik
    env_file:
     - ./.env
    networks:
      - traefik
      - rocketchat_default
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./traefik.toml:/traefik.toml
      - ./ssl:/etc/traefik/ssl
      - ./acme:/etc/traefik/acme
    labels:
      - "traefik.frontend.rule=Host: traefik.chatopswg.xyz"

networks:
  traefik:
    driver: bridge
  rocketchat_default:
    external:
      name: rocketchat_default
